apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: venueflow
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containerConcurrency: 80
      containers:
        - image: IMAGE_URL
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: NODE_ENV
              value: "production"
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
